channels:
  - openeye
  - conda-forge
  - omnia
  - defaults
dependencies:
  - ambertools=21.11
  - anyio=3.4.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - astunparse=1.6.3
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bhmm=0.6.3
  - bleach=4.1.0
  - blosc=1.21.0
  - bokeh=2.4.2
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.10
  - colorama=0.4.4
  - conda=4.11.0
  - conda-package-handling=1.7.3
  - cryptography=36.0.1
  - curl=7.81.0
  - cycler=0.11.0
  - cython=0.29.26
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - deeptime=0.3.1
  - defusedxml=0.7.1
  - dill=0.3.4
  - entrypoints=0.3
  - expat=2.4.2
  - fftw=3.3.10
  - flit-core=3.6.0
  - fontconfig=2.13.1
  - fonttools=4.28.5
  - freetype=2.10.4
  - gettext=0.19.8.1
  - greenlet=1.1.2
  - h5py=3.6.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=68.2
  - idna=3.1
  - importlib-metadata=4.10.0
  - importlib_resources=5.4.0
  - iniconfig=1.1.1
  - ipykernel=6.6.1
  - ipython=7.31.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=4.3.3
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyter_server=1.13.1
  - jupyterlab=3.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.2
  - khronos-opencl-icd-loader=2022.01.04
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.81.0
  - libcxx=12.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libmamba=0.19.1
  - libmambapy=0.19.1
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=13.5
  - libsodium=1.0.18
  - libsolv=0.7.19
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - lzo=2.10
  - mamba=0.19.1
  - markupsafe=2.0.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mdtraj=1.9.7
  - mistune=0.8.4
  - mock=4.0.3
  - mpld3=0.5.7
  - msmtools=1.2.6
  - multiprocess=0.70.12.2
  - munkres=1.1.4
  - mysql-common=8.0.27
  - mysql-libs=8.0.27
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclassic=0.3.4
  - nbclient=0.5.9
  - nbconvert=6.4.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - netcdf-fortran=4.5.3
  - networkx=2.6.3
  - nglview=3.0.3
  - notebook=6.4.6
  - nspr=4.32
  - nss=3.73
  - numexpr=2.8.0
  - numpy=1.22.0
  - ocl_icd_wrapper_apple=1.0.0
  - olefile=0.46
  - openeye-toolkits=2021.2.0
  - openff-forcefields=2.0.0
  - openff-toolkit=0.10.1
  - openff-toolkit-base=0.10.1
  - openjpeg=2.4.0
  - openmm=7.7.0
  - openssl=1.1.1l
  - packaging=21.3
  - packmol=20.010
  - pandas=1.3.5
  - pandoc=2.16.2
  - pandocfilters=1.5.0
  - parmed=3.4.3
  - parso=0.8.3
  - pathos=0.2.8
  - patsy=0.5.2
  - pcre=8.45
  - pdbfixer=1.8.1
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - pixman=0.40.0
  - pluggy=1.0.0
  - pox=0.3.0
  - ppft=1.6.6.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - prompt_toolkit=3.0.24
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.11.0
  - py3dmol=1.7.0
  - pybind11-abi=4
  - pycairo=1.20.1
  - pycosat=0.6.3
  - pycparser=2.21
  - pyemma=2.5.10
  - pygments=2.11.2
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.5
  - python=3.9.9
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.12.9
  - qtconsole=5.2.2
  - qtconsole-base=5.2.2
  - qtpy=2.0.0
  - rdkit=2021.09.3
  - readline=8.1
  - reportlab=3.5.68
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.27.1
  - ruamel_yaml=0.15.80
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=60.3.1
  - six=1.16.0
  - smirnoff99frosst=1.1.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlalchemy=1.4.29
  - sqlite=3.37.0
  - statsmodels=0.13.1
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing_extensions=4.0.1
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xmltodict=0.12.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxt=1.2.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yaml-cpp=0.6.3
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.1
